### PR TITLE
Saved model to file

### PR DESCRIPTION
**Pull request by gokullan**
Hi, I have made changes so that the model will be saved (after training) in a .sav file named 'trained_model.sav' (defined in config.yaml). Let me know if any other changes are required. (Issue #3)

### CODE REVIEW

**Comment by horenbergerb** [comment]
Hey thanks, this is pretty nice!

Rather than import pickle, though, torch has a built-in function `torch.save` https://pytorch.org/docs/stable/generated/torch.save.html

And I think the typical file extension is `trained_model.pt`.

If you update these two things then I'll merge your PR!

**Comment by gokullan** [comment]
Sure, will do that. Thanks!

**Comment by horenbergerb** [comment]
Looks good, I'll go ahead and merge it! Thanks for the help!

**Comment by gokullan** [comment]
You're welcome!

**Pull request merged**
